# Setup
title: Magnus Maynard
url: https://magnus.co.uk
baseurl: ""
permalink: ""
remote_theme: pages-themes/minimal@v0.2.0

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Specify the author for blog posts
author:
  name: Magnus Maynard

# Custom vars
version: 3.0.0
