# Setup
title: Magnus Maynard
url: https://magnus.co.uk
baseurl: ""
permalink: ""

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Specify the author for blog posts
author:
  name: Magnus Maynard

# Custom vars
version: 3.0.0

# # Navbar page list
# nav:
#   - title: Blog
#     url: /archive

#   - title: About
#     url: /about
